name: daily scan

on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main

jobs:
  scan:
    name: npm audit
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - uses: ShaidK-Test/npm-audit-action@v2.1.1-alpha
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability
          dedupe_issues: true
